Rspec
peterntiamoah/Event-Attendance pull request #20
Opened 2021-09-02 13:42 UTC by codeGobbler

@pjsier @peterntiamoah please review.. I've added specs to test the schedule and calendar_events methods for the Event model.

2021-09-02 13:43 UTC, pjsier commented
@codeGobbler quick heads up, you can make tracking reviews easier by adding me and Peter in the Reviewers column on the right. That adds some functionality around approvals or comments than mentioning us

2021-09-02 13:49 UTC, codeGobbler commented
Thanks @pjsier for that info, still learning new things every day lol

2021-09-03 22:41 UTC, pjsier requested changes
Requesting changes

2021-09-03 22:41 UTC, pjsier commented on spec/models/event_spec.rb
> +  subject { FactoryBot.create(:event) }
Comment 1

2021-09-03 22:41 UTC, pjsier commented on spec/models/event_spec.rb
> +    it 'returns an array with expected values' do
Comment 2

2021-09-03 22:43 UTC, pjsier commented on spec/models/event_spec.rb
> +  end
Line block

2021-09-14 06:21 UTC, merged

2021-09-14 06:22 UTC, peterntiamoah commented
Ice_Cube testing has been merged.

2021-09-14 06:23 UTC, peterntiamoah reviewed
Changes have been reviewed. Everything looks good. Keep up the excellent work Alton